### PR TITLE
updated jade and fixed a problem with normalization

### PR DESCRIPTION
**Pull request by capaj**
probably systemjs changed the API since the last time this plugin tests were run

### CODE REVIEW

**Comment by johnsoftek** [comment]
@capaj Do you still need this PR? If so, more details please and a way to reproduce the problem.

**Comment by crissdev** [comment]
@johnsoftek Simple repro available here >> https://github.com/crissdev/jspm-jade-plugin-buggy

``` js
git clone https://github.com/crissdev/jspm-jade-plugin-buggy
cd jspm-jade-plugin-buggy
./node_modules/.bin/jspm update
npm install 
npm start
```

The error message will be visible in browser's console and in the page.

**Comment by johnsoftek** [comment]
@crissdev Two problems: you need to run:

```
jspm install
```

Also, when you import a Jade file, it returns a function, so you need to call it:

```
import content from './test.jade!';

console.log(content());
document.body.appendChild(document.createTextNode(content()));
```

**Comment by crissdev** [comment]
@johnsoftek Thanks. It seems the bug is present only when using the bits in the `master` branch. I've updated the repository in case you want to take a look at.

**Comment by johnsoftek** [comment]
@crissdev I ran git pull. Same results. Are you sure you are running jspm install rather than npm install?

**Comment by crissdev** [comment]
@johnsoftek Yes, for sure. It's not the first time I use jspm.

``` sh
git clone https://github.com/crissdev/jspm-jade-plugin-buggy
cd jspm-jade-plugin-buggy
npm install 
./node_modules/.bin/jspm update
npm start
```

**Comment by johnsoftek** [comment]
What version jspm?

**Comment by johnsoftek** [comment]
@guybedford For plugin-jade, I import the Jade compiler. Package.json has:

```
    "dependencies": {
      "jade": "github:johnsoftek/plugin-jade@^0.5.0",
      "jade-compiler": "npm:jade@^1.11.0"
    },
```

I also need to import the Jade runtime. Previously, I used System.normalize('jade-compiler', module.id) to locate the Jade path and append '/lib/runtime.js' for the import. System.normalize now returns jspm/packages/jade@1.11.0.js rather than a directory. Is there a tidy way to generate the path jspm/packages/jade@1.11.0/lib/runtime.js i.e. '/lib/runtime.js' relative to jade-compiler root?

**Comment by guybedford** [comment]
@johsoftek you should be able to do `System.normalize('jade-compiler/lib/runtime.js', module.id)` here.

**Comment by johnsoftek** [comment]
@guybedford Excellent! That worked so well.

**Comment by johnsoftek** [comment]
@guybedford Thanks! It worked without the .js: `System.normalize('jade-compiler/lib/runtime', module.id)`

**Comment by crissdev** [comment]
@johnsoftek Any chance of publishing an update? Thanks.

**Comment by johnsoftek** [comment]
@crissdev I'm on it.

**Comment by johnsoftek** [comment]
Fixed by commit https://github.com/johnsoftek/plugin-jade/commit/bbd617c7d23aff764aea5cb437badf6ffd6a44ef

**Pull request closed without merging**
